version: '4.31.0'

services:
  db:
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: emailRabbit
      MYSQL_PASSWORD: senha
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: